### ISSUE TITLE
this module is not working

### ISSUE THREAD

**Issue by Elema82** [Smile-SA/magento2-module-store-locator#97] opened 2020-03-26 18:15 UTC
<img width="763" alt="Captura de Pantalla 2020-03-26 a la(s) 15 13 17" src="https://user-images.githubusercontent.com/25822930/77681696-8070ff80-6f74-11ea-9757-c2842cf199bf.png">

Magento 2.3.3
when i try to install this modules the installation show this error

**Comment by fnogatz** [comment] 2020-03-26 18:44
This is a duplicate of #93.

**Comment by Fdec** [comment] 2020-03-26 18:47
Hi guys

I will work on a fix tomorrow.
Stay tuned

Le jeu. 26 mars 2020 à 19:45, Falco Nogatz <notifications@github.com> a
écrit :

**Closed** 2020-03-27 07:08 UTC
